name: CI - Build & Deploy Chatwoot

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: registry.whitelabel.lat/whitelabel-ai/crm-chatwoot-whitelabel

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to private registry
        uses: docker/login-action@v2
        with:
          registry: registry.whitelabel.lat
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Swarm (SSH)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            echo "Logging in to registry on remote host..."
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.whitelabel.lat -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

            IMAGE=${{ env.IMAGE_NAME }}:${{ github.sha }}
            echo "Pulling image ${IMAGE} on remote host..."
            docker pull ${IMAGE}

            # Ajusta el nombre del servicio o stack
            SERVICE_NAME="crm_chatwoot_whitelabel_app"

            echo "Updating service ${SERVICE_NAME} to image ${IMAGE}..."
            # Actualiza APP
            if ! docker service update --image ${IMAGE} crm_chatwoot_whitelabel_app; then
              echo "Service update failed for APP, redeploy stack manually..."
              exit 1
            fi

            # Actualiza SIDEKIQ
            if ! docker service update --image ${IMAGE} crm_chatwoot_whitelabel_sidekiq; then
              echo "Service update failed for SIDEKIQ, redeploy stack manually..."
              exit 1
            fi




            echo "Deploy finished."
